Wiki_dota/config/routes.rb
Rails.application.routes.draw do

  devise_for :users
  resources :heros do
    resources :reviews, except: [:show, :index]
  end

  get 'pages/about'

  get 'pages/contact'

  root 'pages#about'

end

Wiki_dota/app/models/hero.rb
class Hero < ActiveRecord::Base
  mount_uploader :image, ImageUploader

  has_many :reviews

  def self.search(search)
    where("name LIKE ?", "%#{search}%")
  end

  validates :name, :main_att, :str_base, :int_base, :agi_base, :image, :coment, presence: true
  validates :str_base, :agi_base, :int_base, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 1,
    less_than_or_equal_to: 100,
    message: "Apenas números entre 0 e 100"
  }
end

Wiki_dota/app/models/review.rb
class Review < ActiveRecord::Base
  belongs_to :user
  belongs_to :hero

  validates :rating, :comment, presence: true
  validates :rating, numericality: {
    only_integer: true,
    greater_than_or_equal_to: 1,
    less_than_or_equal_to: 5,
    message: "Apenas números entre 0 e 5"
  }

end

Wiki_dota/app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :reviews, dependent: :destroy

  validates :first_name, :last_name, presence: true
end

Wiki_dota/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
  devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name])
  devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name])
  devise_parameter_sanitizer.permit(:account_update, keys: [:first_name])
  devise_parameter_sanitizer.permit(:account_update, keys: [:last_name])
  end
end

Wiki_dota/app/controllers/heros_controller.rb
class HerosController < ApplicationController
  before_action :set_hero, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :check_user, except: [:index, :show]
  # GET /heros
  # GET /heros.json
  def index
    @heros = Hero.all
      if params[:search]
      @heros = Hero.search(params[:search]).order("created_at DESC")
    else
      @heroes = Hero.all.order('created_at DESC')
    end
  end

  # GET /heros/1
  # GET /heros/1.json
  def show
    @reviews = Review.where(hero_id: @hero.id).order("created_at DESC")
    if @reviews.blank?
      @avg_rating = 0
    else
    @avg_rating = @reviews.average(:rating).round(2)
    end
  end

  # GET /heros/new
  def new
    @hero = Hero.new
  end

  # GET /heros/1/edit
  def edit
  end

  # POST /heros
  # POST /heros.json
  def create
    @hero = Hero.new(hero_params)

    respond_to do |format|
      if @hero.save
        format.html { redirect_to @hero, notice: 'Herói foi criado com sucesso.' }
        format.json { render :show, status: :created, location: @hero }
      else
        format.html { render :new }
        format.json { render json: @hero.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /heros/1
  # PATCH/PUT /heros/1.json
  def update
    respond_to do |format|
      if @hero.update(hero_params)
        format.html { redirect_to @hero, notice: 'Herói foi editado com sucesso.' }
        format.json { render :show, status: :ok, location: @hero }
      else
        format.html { render :edit }
        format.json { render json: @hero.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /heros/1
  # DELETE /heros/1.json
  def destroy
    @hero.destroy
    respond_to do |format|
      format.html { redirect_to heros_url, notice: 'Herói foi excluido com sucesso.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_hero
      @hero = Hero.find(params[:id])
    end

    def check_user
      unless current_user.admin?
        redirect_to root_url, alert: "Desculpe, área apenas para administradores"
      end
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def hero_params
      params.require(:hero).permit(:name, :main_att, :str_base, :int_base, :agi_base, :coment, :image)
    end
end

Wiki_dota/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about
  end

  def contact
  end
end

Wiki_dota/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_review, only: [:edit, :update, :destroy]
  before_action :set_hero
  before_action :authenticate_user!
  before_action :check_user, only: [:edit, :update, :destroy]

  respond_to :html


  def new
    @review = Review.new
    respond_with(@review)
  end

  def edit
  end

  def create
    @review = Review.new(review_params)
    @review.user_id = current_user.id
    @review.hero_id = @hero.id

    @review.save
    respond_with(@hero)
  end

  def update
    @review.update(review_params)
    respond_with(@review)
  end

  def destroy
    @review.destroy
    respond_to do |format|
      format.html { redirect_to hero_path(@hero), notice: 'Comentário apagado com sucesso'}
      format.json { head :no_content}
    end
  end

  private
    def set_review
      @review = Review.find(params[:id])
    end

    def set_hero
      @hero = Hero.find(params[:hero_id])
    end

    def check_user
      unless (@review.user == current_user) || (current_user.admin?)
        redirect_to root_url, alert: "Esse comentário pertence a outra pessoa."
      end
    end

    def review_params
      params.require(:review).permit(:rating, :comment)
    end
end

Wiki_dota/app/helpers/application_helper.rb
module ApplicationHelper
end

Wiki_dota/app/helpers/devise_helper.rb
module DeviseHelper
  def devise_error_messages!
    return "" if resource.errors.empty?

    messages = resource.errors.full_messages.map { |msg| content_tag(:li, msg) }.join
    sentence = I18n.t("errors.messages.not_saved", :count => resource.errors.count,
      :resource => resource.class.model_name.human.downcase)

    html = <<-HTML
    <div class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span>
        <span class="sr-only">Close</span>
      </button>
      <h4>#{sentence}</h4>
      #{messages}
    </div>
    HTML

    html.html_safe
  end
end

Wiki_dota/app/helpers/heros_helper.rb
module HerosHelper
end

Wiki_dota/app/helpers/pages_helper.rb
module PagesHelper
end

Wiki_dota/app/helpers/reviews_helper.rb
module ReviewsHelper
end

Wiki_dota/app/views/heros/_form.html.erb
<%= form_for(@hero, :html => {multipart: true}) do |f| %>
  <% if @hero.errors.any? %>
  <div id="error_explanation" class="alert alert-danger alert-dismissable">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>

      <h4><%= pluralize(@hero.errors.count, "error") %> prohibited this hero from being saved:</h4>

      <ul>
      <% @hero.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :Nome %><br>
    <%= f.text_field :name, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :Atributo_Primário %><br>
    <%= f.text_field :main_att, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :Força_Básica %><br>
    <%= f.text_field :str_base, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :Inteligencia_Básica %><br>
    <%= f.text_field :int_base, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :Agilidade_Básica %><br>
    <%= f.text_field :agi_base, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :Descrição %><br>
    <%= f.text_area :coment, class: "form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :Imagem %><br>
    <%= f.file_field :image, class: "form-control" %>
  </div>
  <div class="actions">
    <%= f.submit "Criar Herói", class:"btn btn-success" %>
  </div>
<% end %>

Wiki_dota/app/views/heros/edit.html.erb
<h1>Editing hero</h1>

<%= render 'form' %>

<%= link_to 'Visualizar', @hero, class: "btn btn-link" %> |
<%= link_to 'Voltar', heros_path, class: "btn btn-link" %>

Wiki_dota/app/views/heros/index.html.erb
<div class="jumbotron">
  <h2>Página dos Heróis</h2>
  <h3>Explore as Histórias de cada herói e conheça mais sobre o jogo.<br>
    Deixe aqui seus comentários a respeito de cada Herói e suas Builds em jogos</h3>
</div>

<div class="form-group ">
  <%= form_tag(heros_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search], placeholder: "Buscar Herói", class: 'form-control' %>
  <% end %>
</div>

<table class="table table-hover table-condensed">
  <thead>
      <tr>
      <th>Nome</th>
      <th>Atributo Primário</th>
      <th>Força Básica</th>
      <th>Inteligencia Básica</th>
      <th>Agilidade Básica</th>
      <% if user_signed_in? && current_user.admin? %>
      <th colspan="2"></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @heros.each do |hero| %>
      <tr>
        <td><%= link_to hero.name, hero %></td>
        <td><%= hero.main_att %></td>
        <td><%= hero.str_base %></td>
        <td><%= hero.int_base %></td>
        <td><%= hero.agi_base %></td>
        <% if user_signed_in? && current_user.admin? %>
        <td><%= link_to 'Editar', edit_hero_path(hero), class: "btn btn-link" %></td>
        <td><%= link_to 'Destruir', hero, method: :delete, data: { confirm: 'Tem Certeza?' }, class: "btn btn-link" %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>
<% if user_signed_in? && current_user.admin? %>
<%= link_to 'Novo Herói', new_hero_path, class: "btn btn-link" %>
<%end%>

<br>

Wiki_dota/app/views/heros/new.html.erb
<h1>New hero</h1>

<%= render 'form' %>

<%= link_to 'Back', heros_path, class: "btn btn-link" %>

Wiki_dota/app/views/heros/show.html.erb
<p id="notice"><%= notice %></p>
<div class="row">
  <div class="col-md-3">
    <%= image_tag @hero.image_url %>

    <h2>
      <%= @hero.name %>
    </h2>

    <div class="star-rating" data-score= <%= @avg_rating %> ></div>
    <p><%= "#{@reviews.length} Comentários" %> </p>

    <p>
      <strong>Atributo Primário:</strong>
      <%= @hero.main_att %>
    </p>

    <p>
      <strong>Força básica base:</strong>
      <%= @hero.str_base %>
    </p>

    <p>
      <strong>Inteligencia básica:</strong>
      <%= @hero.int_base %>
    </p>

    <p>
      <strong>Agilidade básica:</strong>
      <%= @hero.agi_base %>
    </p>

    <%= link_to 'Escrever Comentário', new_hero_review_path(@hero), class: "btn btn-primary" %>

  </div>

  <div class="col-md-9">
    <p>
      <strong><h2>Descrição do Herói:</h2></strong>
      <%= @hero.coment %>
    </p>
    <% if @reviews.blank? %>
    <h3>Sem comentários sobre o Herói. Seja o Primeiro <h3/>
      <% else %>
      <table class= "table">
        <h3>Comentários sobre o Herói: </h3>
        <thead>
          <tr>
            <th class="col-md-3"></th>
            <th class="col-md-9"></th>
          </tr>
        </thead>

        <tbody>
          <% @reviews.each do |review| %>
          <tr>
            <td>
              <h4>
                <%= "#{review.user.first_name.capitalize} #{review.user.last_name.capitalize[0]}." %>
              </h4>
              <p><%= review.created_at.strftime("%-d/%-m/%y") %></p>
            </td>


            <td>
              <div class="star-rating" data-score= <%= review.rating %> ></div>
              <p><%= h(review.comment).gsub(/\n/, '<br/>').html_safe  %></p>
              <% if user_signed_in? %>
                <% if (review.user == current_user) || (current_user.admin?)%>
                  <%= link_to "Editar", edit_hero_review_path(@hero, review) %>
                  <%= link_to "Deletar", hero_review_path(@hero, review), method: :delete %>
                <%end%>
              <%end%>
            </td>
          </tr>
          <% end %>
        </tbody>
      </table>
    <%end %>

  </div>
</div>




<%= link_to 'Edit', edit_hero_path(@hero), class: "btn btn-link" %> |
<%= link_to 'Back', heros_path, class: "btn btn-link" %>

<script>
$('.star-rating').raty({
  readOnly: true,
  path: 'https://s3.amazonaws.com/yap-yelpdemo/stars',
  score: function (){
    return $(this).attr('data-score');
  }
});
</script>

Wiki_dota/app/views/layouts/_bootstrap.html.erb
<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<script  src="http://code.jquery.com/jquery-3.1.1.min.js"  integrity="sha256-hVVnYaiADRTO2PzUGmuLJr8BLUSjGIZsDYGmIJLv2b8="  crossorigin="anonymous"></script>

<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

Wiki_dota/app/views/layouts/_footer.html.erb
<div>
<h4><center><i><p>Corpyright Romeu Carvalho & Carlos Aragon</p></center></i></h4>
</div>

Wiki_dota/app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Wiki Dota", root_path, class: "navbar-brand" %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "Heróis", heros_path %></li>
        <li><%= link_to "Contato", pages_contact_path %></li>
      </ul>
      <form class="navbar-form navbar-left">
        <!-- <div class="input-group">
          <%= form_tag(heros_path, :method => "get", id: "search-form") do %>
          <%= text_field_tag :search, params[:search], placeholder: "Search Heroes", class: 'form-control' %>
          <span class="input-group-btn">
            <%= submit_tag "Search", class: 'btn btn-default' %>
          </span>
          <% end %>
        </div>           -->
      </form>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li><%= link_to "Editar Perfil", edit_user_registration_path %></li>
          <li><%= link_to "Sair", destroy_user_session_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Entrar", new_user_session_path %></li>
          <li><%= link_to "Registrar-se", new_user_registration_path %></li>
        <% end %>

      </ul>
    </div>
  </div>
</nav>

Wiki_dota/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WikiDota</title>
  <%= render 'layouts/bootstrap' %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

</head>
<body>
<%= render 'layouts/navbar' %>
  <div class="container-fluid">

    <% flash.each do |name, msg| %>
      <%if msg.is_a?(String) %>
        <div class="alert alert-<%= name== "notice" ? "success" : "danger" %> alert-dismissable">
          <button type="button" class="close" data-dismiss="alert"><span aria-hidden="true">&times;</span><span class=
            ="sr-only">Close</span></button>
            <%= content_tag :div, msg, :id => "flash_#{name}" %>
        </div>
      <% end %>
    <% end %>

    <%= yield %>
    <%= render 'layouts/footer' %>
  </div>
</body>
</html>

Wiki_dota/app/views/pages/about.html.erb
<div class="jumbotron">
  <h1>Bem-Vindo ao Wiki Dota2!</h1>
  <h2>Wiki <%= link_to"Dota2", "http://www.dota2.com" %> é o melhor jeito de saber mais sobre o melhor <%= link_to"MOBA", "https://pt.wikipedia.org/wiki/Multiplayer_online_battle_arena" %> <a href=""> atual.  </h2>
  <h3>Explore as Histórias de cada herói e conheça mais sobre o jogo.<br>
    Deixe aqui seus comentários a respeito de cada Herói e suas Builds em jogos</h3>
</div>
<%= image_tag("dota2.jpg", size: "1600x650") %>

Wiki_dota/app/views/pages/contact.html.erb
<div class="jumbotron">
  <h1 style="font-size:55px">Mande suas Sugestões</h1>
  <h2>
  Gostou do site?<br>
  Acha que tem algo a melhorar?<br>
  Contate um dos nossos administradores.
</h2>
    <p style="color:white">Romeu Carvalho - romeucarvalho2009@hotmail.com<br>Carlos Aragon - carlosaragon3@hotmail.com</p>
</div>

Wiki_dota/app/views/reviews/_form.html.erb
<%= form_for([@hero, @review]) do |f| %>
  <% if @review.errors.any? %>
    <div id="error_explanation" class="alert alert-danger alert-dismissable">
      <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>

      <h4><%= pluralize(@review.errors.count, "error") %> prohibited this review from being saved:</h4>

      <ul>
      <% @review.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div id="star-rating"></div>

  <div class="form-group">
    <%= f.label :Comentário %>
    <%= f.text_area :comment, class: "form-control" %>
  </div>

  <div class="form-group">
    <%= f.submit "Enviar Comentário", class:"btn btn-success" %>
  </div>
<% end %>

<script>
$('#star-rating').raty({
  path: 'https://s3.amazonaws.com/yap-yelpdemo/stars',
  scoreName: 'review[rating]'
});
</script>

Wiki_dota/app/views/reviews/edit.html.erb
<h1>Editar Comentário</h1>

<%= render 'form' %>


<%= link_to 'Back', hero_path(@hero) %>

Wiki_dota/app/views/reviews/new.html.erb
<h1>Novo Comentário</h1>

<%= render 'form' %>

<%= link_to 'Back', hero_path(@hero) %>